[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [
  ".venv",
  ".git",
  "alembic/versions",  # migration scripts can be verbose
]

# Keep linting pragmatic for now
select = ["E", "F"]
ignore = [
  "E203",  # whitespace before ':' (formatter compat)
  "E266",  # too many leading '#' for block comment
  "E501",  # line length handled by formatter/review
  "F401",  # unused imports (allow while iterating)
  "F403",  # 'from x import *'
  "F405",  # may shadow 'import *' names
]

[tool.ruff.per-file-ignores]
"tests/*" = ["F401", "F811"]

