name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: Lint and Type-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Editable install (packaging sanity)
        run: |
          pip install -e .
      - name: Pre-commit hooks
        run: |
          pre-commit run --all-files --show-diff-on-failure
      - name: Ruff (lint)
        run: ruff check .
      - name: mypy (types)
        env:
          PYTHONPATH: .
        run: mypy app payroll_api

  test:
    name: Build, Migrate, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Compile check
        run: |
          python -m compileall app core gateway payroll_api tests
      - name: Alembic migrate (SQLite)
        env:
          DATABASE_URL: sqlite:///./payroll_portal/app.db
        run: |
          python - << 'PY'
          import os, pathlib
          pathlib.Path('payroll_portal').mkdir(exist_ok=True)
          PY
          alembic upgrade head
      - name: Alembic downgrade/upgrade cycle (sanity)
        env:
          DATABASE_URL: sqlite:///./payroll_portal/app.db
        run: |
          alembic downgrade base
          alembic upgrade head
      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q

  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t payroll-portal-ci:latest .
