name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r payroll_portal/requirements.txt
          pip install pytest
      - name: Compile check
        run: |
          python -m compileall app core gateway payroll_api tests
      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          pytest -q

